# Generated by Django 2.1 on 2018-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('sl', 'Share Link')], max_length=2)),
                ('language_code', models.CharField(choices=[('en', 'English')], max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LanguageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(choices=[('en', 'English')], max_length=2, unique=True)),
                ('json_file', models.FileField(upload_to='language-content')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emailcontent',
            unique_together={('type', 'language_code')},
        ),
    ]
