# Generated by Django 2.1.1 on 2018-09-20 09:39

import content.helper
from django.db import migrations, models
import jsoneditor.fields.django_json_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('share_link', 'Share Link')], max_length=15)),
                ('language_code', models.CharField(choices=[('en', 'English')], max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LanguageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('ui', 'UI'), ('funding_goes', 'Funding Goes')], max_length=15)),
                ('language_code', models.CharField(choices=[('en', 'English')], max_length=2)),
                ('content', jsoneditor.fields.django_json_field.JSONField(default='null', help_text='Enter a valid JSON object')),
            ],
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('home', 'Home')], max_length=15)),
                ('image', models.ImageField(storage=content.helper.OverwriteStorage(), upload_to='media-content')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='languagecontent',
            unique_together={('content_type', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='emailcontent',
            unique_together={('content_type', 'language_code')},
        ),
    ]
