# Generated by Django 2.1.1 on 2018-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecontent',
            name='language_code',
            field=models.CharField(choices=[('en', 'English')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='languagecontent',
            unique_together={('type', 'language_code')},
        ),
    ]
