# Generated by Django 2.1.1 on 2018-09-14 08:24

import content.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagecontent',
            name='json_file',
            field=models.FileField(storage=content.helper.OverwriteStorage(), upload_to='language-content'),
        ),
    ]
