# Generated by Django 2.1.1 on 2018-10-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='slug',
            field=models.SlugField(default='-', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='title',
            field=models.CharField(default='-', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
